# Generated by Django 5.2.12 on 2026-04-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Not Paid'), ('paypal', 'PayPal'), ('gpay', 'Google Pay'), ('card', 'Credit/Debit Card'), ('razorpay', 'Razorpay')], max_length=20, null=True),
        ),
    ]
