# Generated by Django 5.2.12 on 2026-04-23 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_helparticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offers', models.BooleanField(default=True)),
                ('sound', models.BooleanField(default=True)),
                ('vibrate', models.BooleanField(default=False)),
                ('general', models.BooleanField(default=True)),
                ('promo', models.BooleanField(default=False)),
                ('payment', models.BooleanField(default=True)),
                ('update', models.BooleanField(default=True)),
                ('service', models.BooleanField(default=False)),
                ('tips', models.BooleanField(default=False)),
                ('extra_settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preferences',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
