# Generated by Django 5.2.12 on 2026-04-23 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_usernotificationpreferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remember_me', models.BooleanField(default=True)),
                ('biometric_id', models.BooleanField(default=True)),
                ('face_id', models.BooleanField(default=False)),
                ('google_auth_enabled', models.BooleanField(default=False)),
                ('pin_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('extra_settings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Settings',
                'verbose_name_plural': 'Security Settings',
            },
        ),
    ]
